name: ci
on:
  pull_request:
  push:
    tags:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1

      - name: Build and test
        run: bazel test --test_output=errors ...

      - name: Test standalone build
        run: c++ -shared -fPIC -ldl -O2 -DNDEBUG -std=c++17 pthread_trace.cc -o pthread_trace.so

      - name: Shut down bazel
        run: bazel shutdown